### ISSUE TITLE
connection DualShock 4 by Bluetooth ? 

### ISSUE THREAD

**Issue by ozzyOuzo** [JibbSmart/JoyShockLibrary#1]
Hello and congratz for the nice work :)

Do you think you will add the ds4 through bluetooth connection feature soon or later ?

Kind regards,

**Comment by JibbSmart** [comment]
Thanks :) I'm working on it this week, actually. Hopefully no dramas, but it shouldn't be too difficult.

Cheers

**Comment by JibbSmart** [comment]
I've pushed and uploaded a new version that adds DS4 bluetooth support, but it can't set light and rumble when connected by bluetooth for the moment.
