### ISSUE TITLE
How to use JslGetMotionState?

### ISSUE THREAD

**Issue by cacaiocamp** [JibbSmart/JoyShockLibrary#14]
Hello!
First, thanks for all the work on the library. It's awesome!

I'm developing an openFrameworks app using JoyShockLibrary, using only joycons. As the v2 added MOTION_STATE, I've been trying to use it in my app but without success. I'm calling JslGetMotionState(deviceId) every frame to get the lastest motion state data, but all that I get is a 1.0 on quatW and 0 for all the other floats of MOTION_STATE struct, on all frames, no matter what I do with my joycon. 

I do the same thing with JslGetIMUState and this one works just fine. Am I doing something wrong?

Edit: I'm building a windows x64 app, on windows 10 with visual studio 2017, for all that it may count.

**Comment by mromoli** [comment]
Same problem here!

**Comment by JibbSmart** [comment]
Sorry I missed this. I've tested this on I think all of my devices (Joy-Cons, Pro Controller, DualShock 4) and can't reproduce this problem. What controller are you using, and how is it connected (USB or Bluetooth)?

**Comment by mromoli** [comment]
I am using bluetooth connected joycons on Unity x64.
Here the code that I am using:

![image](https://user-images.githubusercontent.com/35196302/95102419-abae8580-0733-11eb-8c9b-537e3be49d88.png)
![image](https://user-images.githubusercontent.com/35196302/95102441-b0733980-0733-11eb-94ff-74a14435794e.png)

motionState will results in 0s and only 1 on the W, imuState is working fine

**Comment by cacaiocamp** [comment]
> Sorry I missed this. I've tested this on I think all of my devices (Joy-Cons, Pro Controller, DualShock 4) and can't reproduce this problem. What controller are you using, and how is it connected (USB or Bluetooth)?

Hi! No problem, thanks for the answer.

Hum... I've tested with two pairs of original Joycons connected via Bluetooth, one pair at a time (the delay of the last connected joycon doesnt affect much my app).
I just connect em, get their color and type and start using JslGetSimpleState, JslGetIMUState and JslGetMotionState every frame. The first two work perfectly. 

I also called JslStartContinuousCalibration to see if that was needed to get valid values, but nothing changed. Maybe that's the case but with some other function? I'll try to take a look at the library code and check this out, as soon as I get the time to do it. I'll also try to build the .dll from the source code provided in the release, maybe I get something diferent.

**Comment by mromoli** [comment]
Hope that this can be helpful, for me after setting a callback with JslSetCallback started working fine!

**Comment by JibbSmart** [comment]
Super helpful, @mromoli ! Thanks for that. I always use the callback, so I didn't even notice that the motion.Update function isn't called unless a callback is set. This will be an easy fix, but I don't want to upload fixes without testing them myself, which I won't be able to do until next week.

**Comment by JibbSmart** [comment]
Sorry it took so long. I _think_ this should do it?
https://github.com/JibbSmart/JoyShockLibrary/releases/tag/v2.0.2

**Comment by cacaiocamp** [comment]
> Sorry it took so long. I _think_ this should do it?
> https://github.com/JibbSmart/JoyShockLibrary/releases/tag/v2.0.2

No problem, and yep, it did!
Thanks!
