### ISSUE TITLE
Request - nonverbose mode / suppress output

### ISSUE THREAD

**Issue by MyHighLow** [JibbSmart/JoyShockLibrary#28]
While the information provided in the console is very helpful, it sometimes gets called between my own program's print statements. The console becomes very confusing - there should be some sort of option to suppress JSL output.

> Attempting USB connection
Getting MAC...
Doing handshake...
Switching baudrate...
Doing handshake...
Only talk HID...
Enabling vibration...
Enabling IMU data...
Getting calibration data...
Could not initialise Pro Controller! Will try again later.
Attempting to re-initialise controller 1114529008
Getting MAC...
Doing handshake...
Switching baudrate...
Doing handshake...
Only talk HID...
Enabling vibration...
Enabling IMU data...
Getting calibration data..

PS - USB connections are working nicely with Pro Controllers, and so is multi-threading support!

**Comment by JibbSmart** [comment]
Hi! What platform are you on? These messages aren't supposed to come through. In my case (JoyShockMapper, Windows), they only come through when I uncomment the line `freopen("CONOUT$", "w", stdout);` in JoyShockLibrary.cpp, which I do sometimes for debugging.

**Comment by MyHighLow** [comment]
I am on Windows 10. That's interesting, I get verbose information in the console every time. I am building using Microsoft Visual C++. I'll just comment `freopen("CONOUT$", "w", stdout);` like you suggested
